# Generated by Django 4.2.6 on 2024-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Other', 'Other')], default='Other', max_length=64),
        ),
    ]
