# Generated by Django 4.2.6 on 2024-03-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_winner_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winner_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
